function createGSRECGfigure(subjectIndex, Y1, ECG1, figureType, GSRyRange)
%CREATEFIGURE(Y1, ECG1)
%  Y1:  vector of y data
%  ECG1:  vector of y data
%  GSRyRange: 40000 for training and testing data, 12 for predicting data

%  Auto-generated by MATLAB on 18-Apr-2015 11:53:07 'PaperOrientation','landscape',

% Create figure
figure1 = figure('PaperPosition',[0 0.25 8.15 5.5],'PaperUnits','inches','PaperSize',[8 6]);

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on','XGrid','on',...
    'OuterPosition',[0 0.5 1 0.5],...
    'FontSize',8);
%% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[0 3001]);
%% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[0 GSRyRange]);
hold(axes1,'all');

% Create plot
plot(Y1,'Parent',axes1);

% Create title
title(['Subject ', num2str(subjectIndex) ,': The Arbitrary[Arb] GSR data'],'Interpreter','none',...
    'LineWidth',1,...
    'FontSize',10,...
    'FontName','Times');
% title('Subject 4 : The Arbitrary[Arb] GSR data','Interpreter','none',...
%     'LineWidth',1,...
%     'FontSize',16,...
%     'FontName','Times');

% Create xlabel
xlabel('Sampling Index','Interpreter','none','LineWidth',1,'FontSize',8,...
    'FontName','Times');

% Create ylabel
ylabel('Arbitrary[Arb] GSR value','Interpreter','none','LineWidth',1,...
    'FontSize',8,...
    'FontName','Times');

% Create axes
axes2 = axes('Parent',figure1,'YGrid','on','XGrid','on',...
    'OuterPosition',[0 0 1 0.5],...
    'FontSize',8);
%% Uncomment the following line to preserve the X-limits of the axes
xlim(axes2,[0 3001]);
%% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes2,[-1000 5000]);
hold(axes2,'all');

% Create title
title(['Subject ', num2str(subjectIndex) ,': The Arbitrary[Arb] ECG data'],'Interpreter','none',...
    'FontSize',10,...
    'FontName','Times');

% Create xlabel
xlabel('Sampling Index','Interpreter','none','FontSize',8,...
    'FontName','Times');

% Create ylabel
ylabel('Arbitrary[Arb] ECG value','Interpreter','none','FontSize',8,...
    'FontName','Times');

% Create plot
plot(ECG1,'Parent',axes2,'DisplayName','ECG4');

% Save figure
filename = ['s', num2str(subjectIndex),'_arbRawGSR&ECG'];
saveas(figure1,filename,figureType)

